name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      current: ${{ steps.current.outputs.version }}
      latest: ${{ steps.latest.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Current Release
        id: current
        run: echo "version=1.2.3" >> $GITHUB_OUTPUT
      - name: Get Latest Release
        id: latest
        run: echo "version=1.2.5" >> $GITHUB_OUTPUT
  confirm:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - run: echo ${{needs.check.outputs.current}} ${{needs.check.outputs.latest}}
